version: "2"
services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - 3000:3000
    volumes:
      - ./data/gogs/data:/data
    restart: always

  drone-server:
    container_name: drone_server
    image: drone/drone:0.8.6
    ports:
      - 8000:8000
    volumes:
      - ./data/drone:/var/lib/drone/
    depends_on:
      - gogs
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_DEBUG=true
      - DRONE_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_PRIVATE_MODE=true
    restart: always

  drone-agent:
    container_name: drone_agent
    image: drone/agent:0.8.6
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_DEBUG=true
    restart: always